function B = B_func(o1,o2)
%B_FUNC
%    B = B_FUNC(O1,O2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Aug-2018 12:49:33

t2 = o2.*2.0;
B = [sin(t2).*-9.87212e-2;sin(o1.*4.0).*(cos(t2)-3.0).*-1.25e-8];
