function M = M_func(o1,o2)
%M_FUNC
%    M = M_FUNC(O1,O2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Aug-2018 12:49:33

t2 = sin(o2);
M = reshape([t2.^2.*-9.872115e-2+1.151416e-1,0.0,0.0,cos(o1.*2.0).*1.434929627468613e-42+9.92245e-2],[2,2]);
